### ISSUE TITLE
StackOverflow story link doesn't work

### ISSUE THREAD

**Issue by AntoineFr** [clarkwinkelmann/clarkwinkelmann.com#1]
Hello,

I visited your website after seing it on Flarum and I found that the Stackoverflow Story link is down, so I just wanted to let you know :)

https://github.com/clarkwinkelmann/clarkwinkelmann.com/blob/master/_data/profiles.yaml#L23-L25

**Comment by clarkwinkelmann** [comment]
Thanks, StackOverflow discontinued that service a while back and I kind of forgot to remove the link :sweat_smile:

**Comment by clarkwinkelmann** [comment]
It wasn't actually fixed yet. But now it's done :hugs:
